CORE_RULES = [
    {
        "id": "OT-NET-DHCP",
        "title": "DHCP/BOOTP observed",
        "filter": "dhcp || bootp",
        "category": "network_services",
        "severity": "medium",
        "reason": "DHCP/BOOTP traffic was observed. In critical OT segments, static addressing is often expected, but exceptions may exist.",
        "recommendation": "Confirm whether DHCP is approved for this OT area.",
    },
    {
        "id": "OT-NET-DISCOVERY",
        "title": "Local discovery/name resolution noise observed",
        "filter": "llmnr || nbns || mdns || ssdp || udp.port == 3702 || udp.port == 5355 || udp.port == 5353 || udp.port == 1900",
        "category": "discovery_noise",
        "severity": "low",
        "reason": "LLMNR/NBNS/mDNS/SSDP/WS-Discovery or similar discovery traffic was observed.",
        "recommendation": "Confirm whether discovery traffic is expected. Disable unnecessary local discovery protocols in OT where possible.",
    },
    {
        "id": "OT-NET-SMB-NETBIOS",
        "title": "SMB/NetBIOS traffic observed",
        "filter": "smb || smb2 || nbss || nbdgm || udp.port == 138",
        "category": "file_sharing",
        "severity": "medium",
        "reason": "SMB/NetBIOS traffic was observed.",
        "recommendation": "Confirm business purpose and restrict SMB/NetBIOS to approved hosts.",
    },
    {
        "id": "OT-NET-PLAINTEXT",
        "title": "Telnet/FTP/TFTP observed",
        "filter": "telnet || ftp || tftp",
        "category": "plaintext_management",
        "severity": "high",
        "reason": "Telnet, FTP or TFTP traffic was observed.",
        "recommendation": "Replace with encrypted alternatives where possible.",
    },
    {
        "id": "OT-NET-RSH",
        "title": "RSH or TCP/514 traffic observed",
        "filter": "rsh || tcp.port == 514",
        "category": "plaintext_management",
        "severity": "medium",
        "reason": "RSH or TCP/514 traffic was observed. This may indicate legacy remote shell or another service using TCP/514.",
        "recommendation": "Confirm business purpose. Disable RSH where possible or restrict legacy access to approved maintenance paths.",
    },
    {
        "id": "OT-NET-HTTP",
        "title": "HTTP traffic observed",
        "filter": "http",
        "category": "plaintext_web",
        "severity": "medium",
        "reason": "HTTP traffic was observed.",
        "recommendation": "Confirm whether HTTP is expected and restrict management interfaces.",
    },
    {
        "id": "OT-NET-TLS",
        "title": "TLS/SSL traffic observed",
        "filter": "tls || ssl",
        "category": "encrypted_web",
        "severity": "info",
        "reason": "TLS/SSL traffic was observed.",
        "recommendation": "Review destinations and validate business purpose.",
    },
    {
        "id": "OT-NET-REMOTE-ADMIN",
        "title": "Remote administration traffic observed",
        "filter": "rdp || vnc || ssh",
        "category": "remote_admin",
        "severity": "medium",
        "reason": "RDP, VNC or SSH traffic was observed.",
        "recommendation": "Confirm remote administration is limited to approved admin paths.",
    },
    {
        "id": "OT-NET-SNMP",
        "title": "SNMP traffic observed",
        "filter": "snmp",
        "category": "monitoring",
        "severity": "medium",
        "reason": "SNMP traffic was observed.",
        "recommendation": "Use SNMPv3 where possible and restrict polling.",
    },
    {
        "id": "OT-NET-DNS",
        "title": "DNS traffic observed",
        "filter": "dns",
        "category": "name_resolution",
        "severity": "info",
        "reason": "DNS traffic was observed.",
        "recommendation": "Validate DNS clients and resolvers.",
    },
    {
        "id": "OT-NET-NTP",
        "title": "NTP traffic observed",
        "filter": "ntp",
        "category": "time_sync",
        "severity": "info",
        "reason": "NTP traffic was observed.",
        "recommendation": "Validate approved internal time sources.",
    },
    {
        "id": "OT-NET-AD",
        "title": "LDAP/Kerberos traffic observed",
        "filter": "ldap || kerberos",
        "category": "active_directory",
        "severity": "medium",
        "reason": "LDAP or Kerberos traffic was observed.",
        "recommendation": "Confirm whether AD integration is expected.",
    },
    {
        "id": "OT-NET-BROADCAST-ARP",
        "title": "Broadcast/ARP traffic observed",
        "filter": "eth.dst == ff:ff:ff:ff:ff:ff || arp",
        "category": "layer2_noise",
        "severity": "info",
        "reason": "Broadcast or ARP traffic was observed.",
        "recommendation": "Review volume and source hosts.",
    },
    {
        "id": "OT-NET-TCP-SYN",
        "title": "TCP SYN connection attempts observed",
        "filter": "tcp.flags.syn == 1 && tcp.flags.ack == 0",
        "category": "connection_attempts",
        "severity": "low",
        "reason": "TCP SYN connection attempts were observed. A high volume across many hosts/ports may indicate scanning or misconfiguration.",
        "recommendation": "Review top sources, destinations and ports for scan-like behavior or broken services.",
    },
    {
        "id": "OT-NET-TCP-RESET",
        "title": "TCP reset traffic observed",
        "filter": "tcp.flags.reset == 1",
        "category": "connection_failures",
        "severity": "low",
        "reason": "TCP reset traffic was observed.",
        "recommendation": "Review whether resets indicate refused services, scans or unstable applications.",
    },
    {
        "id": "OT-NET-ICMP-UNREACHABLE",
        "title": "ICMP unreachable traffic observed",
        "filter": "icmp.type == 3",
        "category": "connection_failures",
        "severity": "low",
        "reason": "ICMP unreachable traffic was observed.",
        "recommendation": "Review unreachable destinations for routing, firewall or service issues.",
    },
    {
        "id": "OT-NET-TCP-QUALITY",
        "title": "TCP retransmission/loss indicators observed",
        "filter": "tcp.analysis.retransmission || tcp.analysis.fast_retransmission || tcp.analysis.lost_segment",
        "category": "capture_quality",
        "severity": "info",
        "reason": "TCP retransmission/loss indicators were observed.",
        "recommendation": "Review capture/network quality.",
    },
    {
        "id": "OT-NET-IPV6",
        "title": "IPv6 traffic observed",
        "filter": "ipv6 || icmpv6",
        "category": "ipv6",
        "severity": "low",
        "reason": "IPv6 traffic was observed.",
        "recommendation": "Confirm whether IPv6 is intentionally managed.",
    },
    {
        "id": "OT-NET-SENTINEL-HASP",
        "title": "Sentinel/HASP licensing broadcast observed",
        "filter": "udp.port == 1947",
        "category": "licensing_discovery",
        "severity": "info",
        "reason": "UDP/1947 traffic was observed, commonly used by Sentinel/HASP licensing.",
        "recommendation": "Confirm which OT/engineering application requires this traffic and whether broadcast scope is acceptable.",
    },
]

_INDUSTRIAL = [
    ("OT-ICS-MODBUS", "modbus", "Modbus TCP observed", "tcp.port == 502"),
    ("OT-ICS-S7", "s7comm", "Siemens S7 observed", "tcp.port == 102"),
    ("OT-ICS-PROFINET", "profinet", "Profinet/PN-RT/PTCP/DCP observed", "pn_rt || pn_dcp || ptcp"),
    ("OT-ICS-ENIP-CIP", "ethernet_ip_cip", "EtherNet/IP / CIP observed", "tcp.port == 44818 || udp.port == 44818 || udp.port == 2222"),
    ("OT-ICS-OPCUA", "opcua", "OPC UA observed", "tcp.port == 4840"),
    ("OT-ICS-OPCDA-DCOM", "opc_da_dcom", "OPC DA / DCOM observed", "dcerpc || epm || tcp.port == 135"),
    ("OT-ICS-DNP3", "dnp3", "DNP3 observed", "tcp.port == 20000 || udp.port == 20000"),
    ("OT-ICS-IEC104", "iec104", "IEC 60870-5-104 observed", "tcp.port == 2404"),
    ("OT-ICS-BACNET", "bacnet", "BACnet/IP observed", "udp.port == 47808"),
    ("OT-ICS-ETHERCAT", "ethercat", "EtherCAT observed", "ecat"),
    ("OT-ICS-FINS", "fins", "Omron FINS observed", "udp.port == 9600 || tcp.port == 9600"),
    ("OT-ICS-MITSUBISHI-SLMP", "mitsubishi_slmp_mc", "Mitsubishi SLMP / MC protocol candidate observed", "tcp.port == 5000 || udp.port == 5000 || tcp.port == 5001 || udp.port == 5001"),
    ("OT-ICS-BECKHOFF-ADS", "beckhoff_ads_ams", "Beckhoff ADS/AMS observed", "tcp.port == 48898"),
    ("OT-ICS-GE-SRTP", "ge_srtp", "GE SRTP observed", "tcp.port == 18245"),
    ("OT-ICS-HART-IP", "hart_ip", "HART-IP candidate observed", "tcp.port == 5094 || udp.port == 5094"),
    ("OT-L2-LLDP-CDP", "lldp_cdp", "LLDP/CDP observed", "lldp || cdp"),
    ("OT-L2-STP", "stp", "STP/RSTP/MSTP observed", "stp || rstp || mstp"),
    ("OT-NET-ROUTING-HA", "routing_ha", "Routing/redundancy protocols observed", "vrrp || hsrp || ospf"),
    ("OT-NET-SYSLOG", "syslog", "Syslog observed", "udp.port == 514 || tcp.port == 514"),
]

INDUSTRIAL_RULES = [
    {
        "id": rid,
        "name": name,
        "title": title,
        "filter": flt,
        "category": "industrial_protocol",
        "severity": "info",
        "reason": f"{title}.",
        "recommendation": "Validate expected sources, destinations and operations.",
    }
    for rid, name, title, flt in _INDUSTRIAL
]

SENSITIVE_RULES = [
    {
        "id": "OT-SENSITIVE-FTP-PASS",
        "title": "FTP credential observed in cleartext",
        "filter": 'ftp.request.command == "USER" || ftp.request.command == "PASS"',
        "fields": ["ftp.request.command", "ftp.request.arg"],
        "severity": "high",
        "reason": "FTP USER/PASS command was observed in cleartext.",
        "recommendation": "Disable FTP or replace with SFTP/SCP. Rotate exposed credentials.",
    },
    {
        "id": "OT-SENSITIVE-HTTP-AUTH",
        "title": "HTTP authentication/cookie/form indicator observed",
        "filter": 'http.authorization || http.cookie || http.request.method == "POST"',
        "fields": ["http.authorization", "http.cookie", "http.request.method", "http.host", "http.request.uri"],
        "severity": "high",
        "reason": "HTTP authentication, cookie or POST indicator was observed.",
        "recommendation": "Validate whether sensitive data is exposed over HTTP.",
    },
    {
        "id": "OT-SENSITIVE-SNMP-COMMUNITY",
        "title": "SNMP community string observed",
        "filter": "snmp.community",
        "fields": ["snmp.version", "snmp.community"],
        "severity": "medium",
        "reason": "SNMP community-based monitoring was observed.",
        "recommendation": "Prefer SNMPv3 and rotate weak/default community strings.",
    },
    {
        "id": "OT-SENSITIVE-TELNET",
        "title": "Telnet traffic observed",
        "filter": "telnet",
        "fields": ["telnet.data"],
        "severity": "high",
        "reason": "Telnet traffic was observed.",
        "recommendation": "Disable Telnet or restrict to approved legacy paths.",
    },
]
